const GITHUB_AUTH_TOKEN = "
const BOT_NUMBER = "PRABATH-MD~PbIlHKYb#Q_K1JwoR_inoD25OQ8cZzCSnJjFT6q3iRyjVn_77KPs"
const SESSION_ID = "923097103041"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
